name: supermarket_app_pro
description: Supermarket App Pro

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.18.28+1

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  google_mlkit_text_recognition: ^0.4.0
  animated_splash_screen: ^1.1.0
  http: ^0.13.5
  url_launcher: ^6.1.6
  google_mobile_ads: ^2.0.1
  in_app_purchase: ^3.0.8
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.5
  new_version: ^0.3.1
  device_info_plus: ^4.1.2
  flutter_phoenix: ^1.1.0
  package_info_plus: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  image_path: "assets/images/sp_logo.png"
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: SourceSans
      fonts:
        - asset: fonts/SourceSansPro-SemiBold.ttf
    - family: Gotham
      fonts:
        - asset: fonts/GothamBook.ttf
